package com.example.financetracker.database.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "budget_table")
data class Budget(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,  // Changed from Int to Long
    val category: String,
    val amount: Double,
    val period: String,
    val autoGenerated: Boolean = false,
    var documentId: String = "",
    val userId: String
)