package com.example.financetracker.database.dao

import androidx.room.*
import com.example.financetracker.database.entity.Budget
import kotlinx.coroutines.flow.Flow

@Dao
interface BudgetDao {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertBudget(budget: Budget): Long

    @Update
    suspend fun updateBudget(budget: Budget)

    @Delete
    suspend fun deleteBudget(budget: Budget)

    @Query("SELECT * FROM budget_table WHERE userId = :userId ORDER BY category")
    fun getAllBudgets(userId: String): Flow<List<Budget>>

    @Query("SELECT * FROM budget_table WHERE userId = :userId ORDER BY category")
    suspend fun getAllBudgetsOneTime(userId: String): List<Budget>

    @Query("DELETE FROM budget_table WHERE userId = :userId AND autoGenerated = :autoGenerated")
    suspend fun deleteAllAutoGeneratedBudgets(userId: String, autoGenerated: Boolean = true)

    @Query("SELECT * FROM budget_table WHERE category = :category AND userId = :userId LIMIT 1")
    suspend fun getBudgetByCategory(category: String, userId: String): Budget?
}